aipinter/camera/forms.py
from flask_wtf import FlaskForm
from wtforms import SelectField, SubmitField

class ObjectDetectionForm(FlaskForm):
    choose_cam = SelectField('Object detection type ')
    submit = SubmitField('choose')

aipinter/forecasting/forms.py
from wtforms.validators import DataRequired
from wtforms import StringField, IntegerField, SubmitField, FloatField
from flask_wtf import FlaskForm
import wtforms


class ForecastingForm(FlaskForm, wtforms.Form):
    suhu_minimum  = wtforms.FloatField('Suhu Minimum', validators=[DataRequired()])
    suhu_maksimum = wtforms.FloatField('Suhu Maksimum', validators=[DataRequired()])
    suhu_rata_rata = wtforms.FloatField('Suhu rata-rata', validators=[DataRequired()])
    kelembapan_rata2x = wtforms.FloatField('Kelembapan rata-rata', validators=[DataRequired()])
    curah_hujan = wtforms.FloatField('Curah hujan', validators=[DataRequired()])
    lama_penyinaran = wtforms.FloatField('Lama Penyinaran', validators=[DataRequired()])
    kecepatan_angin_rata2x = wtforms.FloatField('Kecepatan angin rata-rata', validators=[DataRequired()])
    arah_angin_terbanyak = wtforms.FloatField('Arah angin terbanyak', validators=[DataRequired()])
    kecepatan_angin_terbesar = wtforms.FloatField('Kecepatan angin terbesar', validators=[DataRequired()])
    arah_angin_saat_max = wtforms.FloatField('Arah angin saat kecepatan maksimum', validators=[DataRequired()])
    # submit = SubmitField('Predict')

    def save(self, data):
        self.populate_obj(data)
        
    
    # def __repr__(self):
    #     return f'{self.save(data)} data is added'

aipinter/ocr/forms.py
from flask_wtf import FlaskForm
from wtforms import FileField, TextAreaField, SubmitField
from wtforms.validators import DataRequired


class OCRForm(FlaskForm):
    picture = FileField('Upload image', validators=[DataRequired()])
    description = TextAreaField('Description of image', validators=[DataRequired()])
    submit = SubmitField('Predict', validators=[DataRequired()])

aipinter/blogpost/views.py
from flask import redirect, url_for, render_template, Blueprint, flash, request
from aipinter.blogpost.forms import Post
from aipinter import db
from aipinter.models import BlogPost
from flask_login import current_user, login_required

blogpost = Blueprint('blogpost', __name__)

@blogpost.route('/post', methods=['POST', 'GET'])
@login_required
def post():
    if current_user.is_authenticated:
        form = Post()
        if form.validate_on_submit():
            post = BlogPost(author=form.author.data, title=form.title.data,content=form.content.data)
            db.session.add(post)
            db.session.commit()
            flash('new post was added', 'success')
            return redirect(url_for('core.index'))
        return render_template('post.html', form=form)
    else:
        return redirect(url_for('core.login'))

@blogpost.route('/edit/<int:id>', methods=['POST', 'GET'])
@login_required
def edit(id):
    form = Post()
    post = BlogPost.query.get(id)
    if request.method == 'POST':
        post.author = request.form['author']
        post.title = request.form['title']
        post.content = request.form['content']
        db.session.add(post)
        # db.session.flush()
        db.session.commit()
        flash('post suceessfull edited', 'success')
        return redirect(url_for('core.index'))
    else:
        return render_template('edit_post.html', form=form, post=post)

@blogpost.route('/delete/<int:id>', methods=['POST','GET'])
@login_required
def delete(id):
    post = BlogPost.query.filter_by(id_post=id).first()
    db.session.delete(post)
    db.session.commit()
    flash('Post successfully deleted', 'success')
    return redirect(url_for('core.index'))

@blogpost.route('/search', methods=['POST', 'GET'])
@login_required
def search():
    searchForm = SearchForm()
    post = Post_article.query

    if searchForm.validate_on_submit():
        post = post.filter(Post_article.title.like('%' + searchForm.search.data + '%'))

        post = post.order_by(Post_article.title).all()
        return render_template('search_list.html', posts = post, form = searchForm)
    else:
        return render_template('search.html', form = searchForm)

aipinter/camera/views.py
from sklearn.externals import joblib
from aipinter.camera.forms import ObjectDetectionForm
from sklearn.svm import LinearSVC
from aipinter.camera.hog import HOG 
from aipinter import dataset
from flask import Blueprint, render_template, url_for, request, flash, redirect, jsonify, Response
from flask_login import current_user, login_required
from imutils.video import VideoStream
import imutils
import argparse
import cv2
import mahotas
import face_recognition
import numpy as np
import time

cam = Blueprint('camera', __name__)


@cam.route('/camera', methods=['POST', 'GET'])
@login_required
def camera():
    form_od = ObjectDetectionForm()
    if current_user.is_authenticated == False:
        flash('Please, login first', 'danger')
        return redirect(url_for('users.login'))
    else:
        if request.method == 'POST':
            data_cam = request.form['camera']
            if data_cam == 'SSD MobileNet':
                req = 'ssd'
                return render_template('camera.html', form=form_od, req=req)
            elif data_cam == 'DLIB Face Recognition':
                req = 'dlib'
                return render_template('camera.html', form=form_od, req=req)
            
            elif data_cam == 'ResNet10 Face Recognition':
                req = 'res10'
                return render_template('camera.html', form=form_od, req=req)
            
            else:
                req = 'norm'
                return render_template('camera.html', form=form_od, req=req)
        else:
            return render_template('camera.html', form=form_od, req='norm')

def gen():
    i=1
    while i<10:
        yield (b'--frame\r\n'
            b'Content-Type: text/plain\r\n\r\n'+str(i)+b'\r\n')
        i+=1

def get_frame_ssd():
    camera_port=0
    ramp_frames=100
    camera=cv2.VideoCapture(camera_port) #this makes a web cam object

    i=1

    parser = argparse.ArgumentParser(description='Script to run MobileNet-SSD object detection network ')
    parser.add_argument("--video", help="path to video file. If empty, camera's stream will be used")
    parser.add_argument("--prototxt", default="aipinter/dnn/mobileNet_ssd/MobileNetSSD_deploy.prototxt.txt",
                                    help='Path to text network file: '
                                        'MobileNetSSD_deploy.prototxt for Caffe model or '
                                        )
    parser.add_argument("--weights", default="aipinter/dnn/mobileNet_ssd/MobileNetSSD_deploy.caffemodel",
                                    help='Path to weights: '
                                        'MobileNetSSD_deploy.caffemodel for Caffe model or '
                                        )
    # parser.add_argument("--thr", default=0.2, type=float, help="confidence threshold to filter out weak detections")
    args = parser.parse_args()


    CLASSES = ["background", "aeroplane", "bicycle", "bird", "boat",
        "bottle", "bus", "car", "cat", "chair", "cow", "diningtable",
        "dog", "horse", "motorbike", "person", "pottedplant", "sheep",
        "sofa", "train", "tvmonitor"]
    COLORS = np.random.uniform(0, 255, size=(len(CLASSES), 3))

    # load our serialized model from disk
    # print("[INFO] loading model...")
    net = cv2.dnn.readNetFromCaffe(args.prototxt, args.weights)

    # load the input image and construct an input blob for the image
    # by resizing to a fixed 300x300 pixels and then normalizing it
    # (note: normalization is done via the authors of the MobileNet SSD
    # implementation)
    # image = cv2.imread(args["image"])
    # (h, w) = image.shape[:2]
    # blob = cv2.dnn.blobFromImage(cv2.resize(image, (300, 300)), 0.007843, (300, 300), 127.5)

    # pass the blob through the network and obtain the detections and
    # predictions
    # print("[INFO] computing object detections...")


    while True:
        # image = cv2.imread(args["image"])
        retval, image = camera.read()
        (h, w) = image.shape[:2]
        blob = cv2.dnn.blobFromImage(cv2.resize(image, (100, 100)), 0.007843, (300, 300), 127.5)
        net.setInput(blob)
        detections = net.forward()

        # loop over the detections
        for i in np.arange(0, detections.shape[2]):
            # extract the confidence (i.e., probability) associated with the
            # prediction
            confidence = detections[0, 0, i, 2]

            # filter out weak detections by ensuring the `confidence` is
            # greater than the minimum confidence
            if confidence > 0.2:
                # extract the index of the class label from the `detections`,
                # then compute the (x, y)-coordinates of the bounding box for
                # the object
                idx = int(detections[0, 0, i, 1])
                box = detections[0, 0, i, 3:7] * np.array([w, h, w, h])
                (startX, startY, endX, endY) = box.astype("int")

                # display the prediction
                label = "{}: {:.2f}%".format(CLASSES[idx], confidence * 100)
                print("[INFO] {}".format(label))
                cv2.rectangle(image, (startX, startY), (endX, endY),
                    COLORS[idx], 2)
                y = startY - 15 if startY - 15 > 15 else startY + 15
                cv2.putText(image, label, (startX, y),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.5, COLORS[idx], 2)
        
        imgencode=cv2.imencode('.jpg',image)[1]
        stringData=imgencode.tostring()
        yield (b'--frame\r\n'
            b'Content-Type: text/plain\r\n\r\n'+stringData+b'\r\n')
        i+=1

    del(camera)


def get_frame_dlib():
    camera_port=0
    ramp_frames=100
    camera=cv2.VideoCapture(camera_port) #this makes a web cam object

    i=1

    # codingan face recognition
    obama_image = face_recognition.load_image_file('aipinter/dataset/face-datasets/toufan/10.jpg')
    obama_face_encoding = face_recognition.face_encodings(obama_image)[0]

    # Load a second sample picture and learn how to recognize it.
    biden_image = face_recognition.load_image_file("aipinter/dataset/face-datasets/cezar/1.jpg")
    biden_face_encoding = face_recognition.face_encodings(biden_image)[0]

    # Create arrays of known face encodings and their names
    known_face_encodings = [
        obama_face_encoding,
        biden_face_encoding
    ]
    known_face_names = [
        "Toufan",
        "Cezar"
    ]

    # Initialize some variables
    face_locations = []
    face_encodings = []
    face_names = []
    process_this_frame = True


    while True:
        retval, frame = camera.read()
        frame = cv2.resize(frame,(400, 320))
        # im = cv2.cvtColor(im, cv2.COLOR_BGR2HSV)
        small_frame = cv2.resize(frame, (0, 0), fx=0.25, fy=0.25)

        # Convert the image from BGR color (which OpenCV uses) to RGB color (which face_recognition uses)
        rgb_small_frame = small_frame[:, :, ::-1]

        # Only process every other frame of video to save time
        if process_this_frame:
            # Find all the faces and face encodings in the current frame of video
            face_locations = face_recognition.face_locations(rgb_small_frame, model='cnn')
            face_encodings = face_recognition.face_encodings(rgb_small_frame, face_locations)

            face_names = []
            for face_encoding in face_encodings:
                # See if the face is a match for the known face(s)
                matches = face_recognition.compare_faces(known_face_encodings, face_encoding)
                name = "Unknown"

                # If a match was found in known_face_encodings, just use the first one.
                if True in matches:
                    first_match_index = matches.index(True)
                    name = known_face_names[first_match_index]

                face_names.append(name)

        process_this_frame = not process_this_frame


        # Display the results
        for (top, right, bottom, left), name in zip(face_locations, face_names):
            # Scale back up face locations since the frame we detected in was scaled to 1/4 size
            top *= 4
            right *= 4
            bottom *= 4
            left *= 4

            # Draw a box around the face
            cv2.rectangle(frame, (left, top), (right, bottom), (0, 0, 255), 2)

            # Draw a label with a name below the face
            # cv2.rectangle(frame, (left, top - 35), (right, top), (0, 0, 255), cv2.FILLED)
            font = cv2.FONT_HERSHEY_DUPLEX
            # cv2.putText(frame, name, (left + 6, top - 6), font, 1.0, (255, 255, 255), 1)
    
        imgencode=cv2.imencode('.jpg',frame)[1]
        stringData=imgencode.tostring()
        yield (b'--frame\r\n'
            b'Content-Type: text/plain\r\n\r\n'+stringData+b'\r\n')
        i+=1

    del(camera)


# CAMERA NORMAL / BIASA
def get_frame_norm():
    camera_port=0
    ramp_frames=100
    camera=cv2.VideoCapture(camera_port) #this makes a web cam object
    i=1
    while True:
        retval, frame = camera.read()
        frame = cv2.resize(frame,(400, 320))
    
        imgencode=cv2.imencode('.jpg',frame)[1]
        stringData=imgencode.tostring()
        yield (b'--frame\r\n'
            b'Content-Type: text/plain\r\n\r\n'+stringData+b'\r\n')
        i+=1

    del(camera)

def get_frame_res10():

    camera_port=0
    ramp_frames=100
    camera=cv2.VideoCapture(camera_port) #this makes a web cam object


    ap = argparse.ArgumentParser()
    ap.add_argument("--prototxt", default="aipinter/dnn/res10/deploy.prototxt.txt",
        help="path to Caffe 'deploy' prototxt file")
    ap.add_argument("--model", default="aipinter/dnn/res10/res10_300x300_ssd_iter_140000.caffemodel",
        help="path to Caffe pre-trained model")
    ap.add_argument("--confidence", type=float, default=0.5,
        help="minimum probability to filter weak detections")
    args = vars(ap.parse_args())

    # load our serialized model from disk
    print("[INFO] loading model...")
    try:

aipinter/users/views.py
from flask import Blueprint, render_template, url_for, redirect, request, flash
from flask_login import login_user, logout_user, current_user, login_required
from werkzeug.security import generate_password_hash, check_password_hash
from aipinter.models import User, BlogPost
from aipinter.users.forms import RegisterForm, LoginForm, UpdateUserForm
from aipinter import db

users = Blueprint('users', __name__)

@users.route('/register', methods=['POST', 'GET'])
def register():

    if current_user.is_authenticated:
        return redirect(url_for('core.index'))

    form = RegisterForm()

    if form.validate_on_submit():
        user = User(email=form.email.data, 
        username=form.username.data, 
        password=form.password.data)
        db.session.add(user)
        db.session.commit()
        flash('Thanks for registration', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', form=form)

@users.route('/login', methods=['POST', 'GET'])
def login():
    
    if current_user.is_authenticated:
        return redirect(url_for('core.index'))
        
    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        try:
            if user.check_password(form.password.data) and user is not None:
            # if check_password_hash(user.password, form.password.data) and user is

                login_user(user)
                flash('login success', 'success')

                next = request.args.get('next')

                if next == None or not next[0] == '/':
                    next = url_for('core.index')
                
                return redirect(next)
        except:
            flash('there is no any acount registered in this app, be the first one !!', 'danger')
            return redirect(url_for('users.register'))
    return render_template('login.html', form=form)

@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('users.login'))

# @user.route('/account', methods=['POST', 'GET'])
# def account():

#     form = UpdateUserForm()

#     if form.validate_on_submit():
        

aipinter/templates/chatbot.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">AiPi Bot</legend>
                <!-- {{ form.user.label(class='form-control-label') }} -->
                <!-- {{ form.user.label(class='form-control-label') }} -->
                <p>This is bot</p> 
        </fieldset>
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">User not Bot</legend>
                <!-- {{ form.user.label(class='form-control-label') }} -->
                {{ form.user(class='form-control form-control-lg') }}
            
        </fieldset>
        <fieldset>
                {{ form.submit(class='btn btn-outline-info') }}
        </fieldset>
    </form>
</div>

{% endblock %}

aipinter/templates/edit_post.html
{% extends "layout.html" %}
{% block content %}

<div class="content-section">

    <form action="" method="POST" enctype="multipart/form-data">

        {{ form.hidden_tag() }}
    {% if post %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Add Post</legend>
                {{ form.title.label(class='form-control-label') }}
                <input type="text" class="form-control form-control-lg" name="title" value="{{ post.title }}">


        </fieldset>
        <fieldset class="form-group">
                {{ form.author.label(class='form-control-label') }}
                <input type="text" class="form-control form-control-lg" name="author" value="{{ post.author }}">

        </fieldset>
        <fieldset class="form-group">
                {{ form.content.label(class='form-control-label') }}
                <textarea name="content" cols="30" rows="10" class="form-control form-control-lg">{{ post.content }}</textarea>
        {% endif %}
        </fieldset>
        <fieldset class="form-group">
            <input type="submit" class="btn btn-outline-info" value="Update">
        </fieldset>

    </form>
</div>


{% endblock %}

aipinter/templates/forecasting.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">

    <form action="" method="POST" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
                <legend class="border-bottom mb-4">Forecasting</legend>
        </fieldset>
        {% for field in form %}
        <fieldset class="form-group">
                {{ field.label(class='form-control-label') }}
                {{ field(class='form-control form-control-lg') }}
        </fieldset>        
        {% endfor %}
        <fieldset class="form-group">
            <input type="submit" class="btn btn-outline-info" value="Update">
        </fieldset>
    </form>
    
</div>

{% endblock %}

aipinter/templates/layout (copy).html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    {% if title %}
        <title>Toufani - {{ title }}</title>
    {% else %}
        <title>Toufani</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
          <!-- <nav class="navbar navbar-light fixed-top" style="background-color: #e3f2fd;"> -->
              <!-- Navbar content -->
            
        <div class="container">
          <a class="navbar-brand mr-4" href="/"><img src="http://localhost:5000/static/img/logo1.png" alt="" width="130px" height="25px"></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">

            <!-- Navbar Right Side -->
            {% if current_user.is_authenticated %}
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="/cvision">Vision</a>
              <a class="nav-item nav-link" href="/camera">Camera</a>
              <a class="nav-item nav-link" href="/ocr">OCR</a>
              <a class="nav-item nav-link" href="/chatbot">Chatbot</a>
              <a class="nav-item nav-link" href="/forecasting">Forecasting</a>
            </div>

            <div class="navbar-nav">
                <a class="nav-item nav-link" href="#">Post</a>
                <a class="nav-item nav-link" href="{{url_for('users.logout')}}">Log out</a>
              

            </div>

            {% else %}
            <div class="navbar-nav mr-auto"></div>
            <div class="navbar-nav">
              <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
              <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
            </div>
            {% endif %}
          </div>
        </div>
      </nav>
    </header>

    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          <!-- FLASH -->
            {% with messages = get_flashed_messages(with_categories=true) %}
              {% if messages %}
                {% for category, message in messages %}
                  <div class="alert alert-{{ category }}"> {{ message }} </div>
                {% endfor %}
              {% endif %}
            {% endwith %}
          {% block content %}
          
          {% endblock %}
        </div>

        
        
          </div>
        </div>
      </div>
    </main>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

aipinter/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    {% if title %}
        <title>Toufani - {{ title }}</title>
    {% else %}
        <title>Toufani</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
          <!-- <nav class="navbar navbar-light fixed-top" style="background-color: #e3f2fd;"> -->
              <!-- Navbar content -->
            
        <div class="container">
          <a class="navbar-brand mr-4" href="/"><img src="http://localhost:5000/static/img/logo1.png" alt="" width="130px" height="25px"></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">

            <!-- Navbar Right Side -->
            {% if current_user.is_authenticated %}
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="/cvision">Classifier</a>
              <a class="nav-item nav-link" href="/camera">Camera</a>
              <a class="nav-item nav-link" href="/ocr">OCR</a>
              <a class="nav-item nav-link" href="/chatbot">Chatbot</a>
              <a class="nav-item nav-link" href="/forecasting">Forecasting</a>
            </div>

            <div class="navbar-nav">
                <a class="nav-item nav-link" href="{{ url_for('blogpost.post') }}">Post</a>
                <a class="nav-item nav-link" href="{{url_for('users.logout')}}">Log out</a>
              

            </div>

            {% else %}
            <div class="navbar-nav mr-auto"></div>
            <div class="navbar-nav">
              <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
              <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
            </div>
            {% endif %}
          </div>
        </div>
      </nav>
    </header>

    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          <!-- FLASH -->
            {% with messages = get_flashed_messages(with_categories=true) %}
              {% if messages %}
                {% for category, message in messages %}
                  <div class="alert alert-{{ category }}"> {{ message }} </div>
                {% endfor %}
              {% endif %}
            {% endwith %}
          {% block content %}{% endblock %}
        </div>
        <div class="col-md-4">
          <div class="content-section">
            <h4>Our Engine</h4>
            <p class='text-muted'>Machine learning engine services.
              <ul class="list-group">
                  {% if current_user.is_authenticated %}
                <li class="list-group-item list-group-item-light"><a href="{{ url_for('vision.vision_list') }}">Vision List</a></li>
                <li class="list-group-item list-group-item-light"><a href="{{ url_for('ocreg.ocr_list') }}">OCR List</a></li>
                <li class="list-group-item list-group-item-light"><a href="{{ url_for('forecasting.forecasting_list') }}">Forecasting List</a></li>
                {% else %}
                <li class="list-group-item list-group-item-light">Vision</li>
                <li class="list-group-item list-group-item-light">Chatbot</li>
                <li class="list-group-item list-group-item-light">Forecasting</li>
                <li class="list-group-item list-group-item-light">etc</li>
                {% endif %}
                
              </ul>
            </p>
          </div>
        </div>
      </div>
    </main>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

aipinter/templates/lihat_img.html
{% extends "layout.html" %}
{% block content %}

<div class="content-section">
    <img class="img-circle" alt="" src="/static/output_ocr/ocrimage.jpg" width="30%" style="text-align:center ; border-radius: 10%;; margin-left:auto ; margin-right:auto"> 
    <blockquote class="blockquote">
        <footer class="blockquote-footer">test</footer>
    </blockquote>
</div>

{% endblock %}